CREATE TABLE spans (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    app_id VARCHAR(64) NOT NULL DEFAULT 'main',
    user_id VARCHAR(64) DEFAULT '',
    trace_id CHAR(32) NOT NULL,
    span_id CHAR(16) NOT NULL,
    parent_span_id CHAR(16),
    session_id VARCHAR(64) NOT NULL,
    turn_id VARCHAR(64) DEFAULT '',
    turn_number INT DEFAULT 0,
    operation_name VARCHAR(128) NOT NULL,
    start_time DATETIME(3) NOT NULL,
    end_time DATETIME(3),
    duration_ms INT,
    status VARCHAR(10) DEFAULT 'running',
    attributes JSON,
    INDEX idx_app_start_time (app_id, start_time),
    INDEX idx_trace_id (trace_id),
    INDEX idx_session_turn (session_id, turn_number),
    INDEX idx_start_time (start_time)
);

CREATE TABLE session_metrics (
    session_id VARCHAR(64) PRIMARY KEY,
    trace_id CHAR(32) NOT NULL,
    app_id VARCHAR(64) NOT NULL DEFAULT 'main',
    user_id VARCHAR(64),
    model VARCHAR(32),
    status VARCHAR(16) DEFAULT 'running',
    total_turns INT DEFAULT 0,
    total_prompt_tokens BIGINT DEFAULT 0,
    total_completion_tokens BIGINT DEFAULT 0,
    token_budget BIGINT DEFAULT 0,
    sum_llm_latency_ms BIGINT DEFAULT 0,    -- 用于算 avg
    sum_first_token_ms BIGINT DEFAULT 0,
    max_llm_latency_ms INT DEFAULT 0,
    min_llm_latency_ms INT DEFAULT 999999,
    total_tool_calls INT DEFAULT 0,
    total_errors INT DEFAULT 0,
    recovery_count INT DEFAULT 0,
    last_recovery_kind VARCHAR(32) DEFAULT '',
    avg_memory_hits REAL DEFAULT 0,
    total_memory_hits INT DEFAULT 0,
    end_reason VARCHAR(32),
    started_at DATETIME(3) NOT NULL,
    ended_at DATETIME(3),
    duration_ms INT DEFAULT 0,
    updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    INDEX idx_session_metrics_trace (trace_id),
    INDEX idx_session_metrics_app_status (app_id, status),
    INDEX idx_session_metrics_updated (updated_at)
);


CREATE TABLE turn_metrics (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    trace_id CHAR(32) NOT NULL,
    session_id VARCHAR(64) NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    turn_id VARCHAR(64) NOT NULL,
    status VARCHAR(16) DEFAULT 'running',
    prompt_tokens INT,
    completion_tokens INT,
    llm_latency_ms INT,
    first_token_ms INT,
    llm_recovery_count INT DEFAULT 0,
    llm_recovery_kind VARCHAR(32) DEFAULT '',
    is_llm_error bool,
    tool_calls_count INT DEFAULT 0,
    tool_calls_status JSON,              -- [{"name":"read_file","status":"success"}, ...]
    memory_hits INT DEFAULT 0,
    memory_retrieval_ms INT,
    is_memory_error bool,
    context_tokens INT,
    context_token_usage INT,
    is_compress BOOL,
    error_count INT DEFAULT 0,
    started_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    ended_at DATETIME(3),
    duration_ms INT DEFAULT 0,
    created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    INDEX idx_turn_metrics_trace (trace_id),
    INDEX idx_session_turn (session_id, turn_number),
    INDEX idx_request_turn (session_id, request_id, turn_number),
    INDEX idx_turn_metrics_status (status, created_at)
);

CREATE TABLE monitor_alerts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    rule_name VARCHAR(64) NOT NULL,
    level VARCHAR(16) NOT NULL,
    trace_id CHAR(32) NOT NULL,
    session_id VARCHAR(64) NOT NULL,
    turn_id VARCHAR(64) DEFAULT '',
    status VARCHAR(16) DEFAULT 'open',
    message VARCHAR(255) NOT NULL,
    observed_value VARCHAR(128) DEFAULT '',
    threshold_value VARCHAR(128) DEFAULT '',
    triggered_at DATETIME(3) NOT NULL,
    resolved_at DATETIME(3),
    payload JSON,
    INDEX idx_alert_rule_status (rule_name, status),
    INDEX idx_alert_session (session_id),
    INDEX idx_alert_triggered_at (triggered_at)
);