global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'codegenx-services'
    static_configs:
      - targets: ['api-gateway:8000', 'user-service:8001', 'ai-service:8002', 'chat-service:8005', 'task-service:8004']
